<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>S</string>
		<string>dasm16</string>
	</array>
	<key>name</key>
	<string>DCPU-16</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#Comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(add|ADD|and|AND|bor|BOR|brk|BRK|dat|DAT|div|DIV|ifb|IFB|ife|IFE|ifg|IFG|ifn|IFN|jmp|JMP|jsr|JSR|mod|MOD|mul|MUL|peek|PEEK|pop|POP|push|PUSH|shl|SHL|shr|SHR|set|SET|sub|SUB|xor|XOR)(l|w|b)?\b</string>
			<key>name</key>
			<string>keyword.mnemonic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(:\w+)</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>constant.numeric.hex.pointer</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>constant.numeric.hex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>0x[0-9A-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(A|B|C|I|J|X|Y|Z)+\b</string>
			<key>name</key>
			<string>constant.register.variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(PC|pc|SP|sp|O|o)\b</string>
			<key>name</key>
			<string>constant.register.other</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dcpu-16</string>
	<key>uuid</key>
	<string>D8985F81-2345-4381-84C0-195B68783AF2</string>
</dict>
</plist>